#!/usr/bin/env ansible-playbook
# tasks/azure_create_service_principle.yml
---

# Create a Service Principle for use deploying on Azure.

- name: Create a Service Principle on Azure.
  command: 'az ad sp create-for-rbac --name "{{ azure_service_principle_name }}" > ~/.azure/service_principle.txt'
  when: "{{ azure_create_new_service_principle }}" == True
