#!/usr/bin/env ansible-playbook
---

- name: Retrieve Azure's Dynamic Inventory Script.
  get_url: 
    url: "https://raw.githubusercontent.com/ansible/ansible/devel/contrib/inventory/azure_rm.py"
    dest: "~/azure_rm.py"
    mode: "0755"
