#!/usr/bin/env ansible-playbook
# tasks/azure_dynamic_inventory_script.yml
---


- name: Retrieve Azure's Dynamic Inventory Script.
  get_url:
    url: "{{ azure_dynamic_inventory_url }}"
    dest: "~/azure_rm.py"
    mode: "0755"
