#!/usr/bin/env ansible-playbook
---

- name: Create an Azure resource group "{{ azure_rg }}" for running the Virtual Machines
  azure_rm_resourcegroup:
    name: "{{ azure_rg }}"
    location: "{{ azure_rg_location }}"
    tags:
      testing: container-linux
      delete: never

- name: Create an Azure Virtual Network "{{ azure_rg_virt_net_cidr }}"
  azure_rm_virtualnetwork:
    resource_group: "{{ azure_rg }}"
    name: "{{ azure_rg_virt_net_name }}"
    address_prefixes: "{{ azure_rg_virt_net_cidr }}"


- name: Add subnet for Container Linux VMs to "{{ azure_rg_virt_net_name }}"
  azure_rm_subnet:
    resource_group: "{{ azure_rg }}"
    name: "{{ azure_rg_virt_subnet_name }}"
    address_prefix: "{{ azure_rg_virt_subnet_addr }}"
    virtual_network: "{{ azure_rg_virt_net_name }}"


- name: "Creating {{ azure_virtual_machines_total }} Azure {{ azure_vm_size }} Container Linux Virtual Machines in zone {{ azure_rg_location }}"
  azure_rm_virtualmachine:
    name: "{{ item }}"
    resource_group: "{{ azure_rg }}"
    vm_size: "{{ azure_vm_size }}"
    managed_disk_type: "{{ azure_managed_disk_type }}"
    admin_username: core
    admin_password: "{{ container_linux_admin_password }}"
    ssh_password_enabled: true
    ssh_public_keys:
      - path: "/home/core/.ssh/authorized_keys"
        key_data: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    subnet_name: "{{ azure_rg_virt_subnet_name }}"
    virtual_network_name: "{{ azure_rg_virt_net_name }}"
    image:
      offer: CoreOS
      publisher: CoreOS
      sku: "{{ container_linux_sku }}"
      version: "{{ container_linux_version }}"
  with_sequence: start=1 end="{{ azure_virtual_machines_total }}" format={{ virtual_machine_naming_prefix }}%02x
  register : azure 
