#!/usr/bin/env ansible-playbook
# tasks/provision_azure_coreos_virtual_machines.yml
---

- name: Create an Azure resource group for running the Virtual Machines
  azure_rm_resourcegroup:
    name: "{{ azure_rg }}"
    location: "{{ azure_rg_location }}"
    tags:
      testing: container-linux
      delete: never

- name: Create an Azure Virtual Network (10.2.0.0/16)
  azure_rm_virtualnetwork:
    resource_group: "{{ azure_rg }}"
    name: "{{ azure_rg_virt_net_name }}"
    address_prefixes: "{{ azure_rg_virt_net_cidr }}"

- name: Add subnet for Flatcar VMs to FlatcarVMsNetwork
  azure_rm_subnet:
    resource_group: "{{ azure_rg }}"
    name: "{{ azure_rg_virt_subnet_name }}"
    address_prefix: "{{ azure_rg_virt_subnet_addr }}"
    virtual_network: "{{ azure_rg_virt_net_name }}"

- name: Create first public IP address for the virtual machine flatcar1.
  azure_rm_publicipaddress:
    resource_group: "{{ azure_rg }}"
    allocation_method: Static
    name: FlatcarPublicIP001
  register: output_ip_address

- name: Dump public IP 1 for flatcar2 VM  which will be created
  debug:
    msg: "The public IP #1 is {{ output_ip_address.state.ip_address }}."

- name: Create second public IP address for the virtual machine flatcar2.
  azure_rm_publicipaddress:
    resource_group: "{{ azure_rg }}"
    allocation_method: Static
    name: FlatcarPublicIP002
  register: output_ip_address

- name: Dump public IP 2 for flatcar2 VM  which will be created
  debug:
    msg: "The public IP #2 is {{ output_ip_address.state.ip_address }}."

- name: Create Network Security Group that allows SSH to the FlatcarVMs
  azure_rm_securitygroup:
    resource_group: "{{ azure_rg }}"
    name: "{{ azure_rg_sec_group }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound

      - name: HTTP
        protocol: Tcp
        destination_port_range: 80
        access: Allow
        priority: 1002
        direction: Inbound

      - name: HTTPS
        protocol: Tcp
        destination_port_range: 443
        access: Allow
        priority: 1003
        direction: Inbound

- name: Creating first virtual network interface. 
  azure_rm_networkinterface:
    resource_group: "{{ azure_rg }}"
    name: FlatcarNIC001
    virtual_network: "{{ azure_rg_virt_net_name }}"
    subnet: "{{ azure_rg_virt_subnet_name }}"
    public_ip_name: FlatcarPublicIP001
    security_group: "{{ azure_rg_sec_group }}"

- name: Creating second virtual network interface.
  azure_rm_networkinterface:
    resource_group: "{{ azure_rg }}"
    name: FlatcarNIC002
    virtual_network: "{{ azure_rg_virt_net_name }}"
    subnet: "{{ azure_rg_virt_subnet_name }}"
    public_ip_name: FlatcarPublicIP002
    security_group: "{{ azure_rg_sec_group }}"

- name: Creating VirtualMachine
  azure_rm_virtualmachine:
    name: "{{ item_key }}"
    resource_group: "{{ azure_rg }}"
    name: flatcar2
    vm_size: "{{ azure_vm_size }}"
    managed_disk_type: "{{ azure_managed_disk_type }}"
    admin_username: core
    admin_password: "{{ container_linux_admin_password }}"
    ssh_password_enabled: true
    ssh_public_keys: 
      - path: "/home/core/.ssh/authorized_keys"
        key_data: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    network_interfaces: "{{ item.value.nic }}"
    image:
      offer: CoreOS
      publisher: CoreOS
      sku: "{{ container_linux_sku }}"
      version: "{{ container_linux_version }}"
  with_dict "{{ container_linux_virtual_machines }}"
